pipeline {

environment {
    imagename = "annetta/site_test"
    registryCredential = 'docker_annetta'
    dockerRemove="docker container rm -f my-site"

}

    agent { node { label 'agent1' } }

    stages {
        stage('Cloning Git') {
            steps {
                git branch: 'main', credentialsId: 'jenkins_master_git', url: 'git@github.com:annetta1/flask_app_01.git'
            }
        }
        
        stage("Build images") {
	    steps {
	      sh "docker-compose build"
              sh "docker-compose push"
	     }
	}




    }
}
